class Return < Command
  def codes
    [   
      "// endFrame=LCL",
      "@LCL",
      "D=M",
      "@R13",
      "M=D",
      "// retAddr = *(endFrame-5)",
      "@5",
      "D=A",
      "@R13",
      "A=M-D",
      "D=M", 
      "@R14",
      "M=D", 
      "// *ARG = pop",
      put_stack_top_value_into_reg_d,
      "@ARG",
      "A=M",
      "M=D",
      "// SP=ARG+1",
      "@ARG",
      "D=M+1",
      "@SP",
      "M=D",
      "// THAT = *(endFramee-1)",
      "@R13", 
      "A=M-1",
      "D=M", 
      "@THAT",
      "M=D",
      "// THIS = *(endFrame-2)",
      "@2",
      "D=A", 
      "@R13",
      "A=M-D",
      "D=M", 
      "@THIS",
      "M=D", 
      "// ARG = *(endFrame-3)",
      "@3", 
      "D=A",
      "@R13", 
      "A=M-D",
      "D=M", 
      "@ARG",
      "M=D", 
      "// LCL = *(endFrame-4)",
      "@4", 
      "D=A",
      "@R13",
      "A=M-D",
      "D=M", 
      "@LCL",
      "M=D", 
      "// goto retAddr",
      "@R14",
      "A=M", 
      "0;JMP",
    ]
  end
end
